# Generated by Django 3.1.1 on 2020-09-12 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PokemonType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Number', models.CharField(max_length=10)),
                ('Generation', models.IntegerField()),
                ('Name', models.CharField(max_length=100)),
                ('Image', models.CharField(max_length=200)),
                ('Created', models.DateTimeField(auto_now_add=True)),
                ('Active', models.BooleanField()),
                ('Types', models.ManyToManyField(to='pokedex.PokemonType')),
            ],
        ),
    ]
